django_v2/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

#from polls import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name="index"),
    url(r'^polls/', include('polls.urls')),
]

polls/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.i18n import urlpatterns

app_name = 'polls'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    #url(r'^$',views.IndexView.as_view(),name='index'),
    
    url(r'^(?P<question_id>[0-9]+)/$',views.details,name="details"),

    #url(r'^(?P<question_id>[0-9]+)/$',views.DetailView.as_view(),name="details"),
    
    url(r'^(?P<person_id>[0-9]+)/person/$',views.persons,name="persons"),


    url(r'^(?P<question_id>[0-9]+)/results/$',views.results,name="results"),
    #url(r'^(?P<question_id>[0-9]+)/results/$',views.DetailView.as_view(),name="results"),
    
    url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote,name="vote"),
    url(r'^file_form/$',views.file_form,name="file_form"),

    url(r'^(?P<person_id>[0-9]+)/form/$',views.get_contactform,name="get_contactform"),  
    
    
]

polls/models.py
from django.db import models
from django.db.models.fields import CharField
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    email_account = models.EmailField(default="huyngo@natrol.vn")
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        #return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    def get_field_question(self):
        return [(field.name,field.value_to_string(self)) for field in Question._meta.fields]
        #return [Question._meta.get_fields()]

class Question_New(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    email_account = models.EmailField(default="huyngo@natrol.vn")

class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
# Create your models here.
    def __str__(self):
        return self.choice_text   


class Person(models.Model):    
    SHIRT_SIZES = (
      ('S','small'),
      ('M','medium'),
      ('L','large'),    
    )        
    shirt_size = models.CharField(max_length=1, choices=SHIRT_SIZES)
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name
    
class Group(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name
    
class Membership(models.Model):
    
    person = models.ForeignKey(Person,on_delete=models.CASCADE)
    group = models.ForeignKey(Group,on_delete=models.CASCADE)
    date_join = models.DateField()
    invite_reason = models.TextField()    
    def __str__(self):
        return "{} {}".format(self.person,self.group)


class Blog(models.Model):

    name = models.CharField(max_length=100) 
    tag_line = models.TextField()   

    def save(self,*args,**kwargs): 

        if self.name == "Huy":
            print("{} don't save his own".format(self.name))
        else:
            super(Blog,self).save(*args,**kwargs)

    def __str__(self):
        return self.name


class Document(models.Model):

    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to='polls/static/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Question, Choice, Blog, Person, Membership
from django.urls import reverse
from django.views import generic
from .form import ContactForm,FileForm
from django.core.mail import send_mail
from django.conf import settings

class IndexView (generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_result'

    def get_queryset(self):
        
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]
    


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/result.html'
    
    
def index(request):
    latest_result = Question.objects.filter(question_text__startswith='what')    
    #latest_result = Question.objects.order_by('-pub_date')[:5]
    v_persons = Person.objects.all()
    v_memberships = Membership.objects.all()
    form = ContactForm()    
    #output = ', '.join(q.question_text for q in latest_result)
    context = {'latest_result': latest_result,'v_persons': v_persons,'v_memberships': v_memberships, 
              'form': form.as_ul()}    
    return render(request,'polls/index.html',context)


def file_form(request):
    
    if request.method == 'POST': 
        file_form = FileForm(request.POST,request.FILES)        
        if file_form.is_valid():
            file_form.save()
            return HttpResponseRedirect(reverse('polls:index'))
    else:
        file_form = FileForm()

    return render(request, 'polls/form.html', {'file_form': file_form.as_ul()})        
 



def get_contactform(request,person_id):    
    if request.method == 'POST':
        form = ContactForm(request.POST)
        


        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            email = form.cleaned_data['sender']
            sender = 'ndahuy@tma.com.vn'
            cc_myself = form.cleaned_data['cc_myself']

            q=Person.objects.get(id=person_id)
            q.name=subject
            q.save()
            #print(request.META)
            print("path = {}".format(request.path))
            print("path_info = {}".format(request.path_info))
            khach = ['huyngo@natrol.vn']
            print(settings.BASE_DIR)
            if cc_myself: 
                khach.append('ndahuy@tma.com.vn')

            #send_mail(subject,message,sender,khach)

            ### Print to console

            """
                Get contactform, handle form and save the status of subject to the name of person. 

            """
            for k, v in form.cleaned_data.items(): 
                print ("Key = {}, value = {}".format(k,v))
            return HttpResponseRedirect(reverse('polls:persons',args = (person_id,)))    
            #return render(request, 'polls/person.html', {'form': form.cleaned_data ,'person': person})        

        else:
            form = ContactForm()
            form.as_ul()

        if  file_form.is_valid():
            file_form.save()
            return HttpResponseRedirect(reverse('polls:persons',args = (person_id,)))  



            
    else:         
        form = ContactForm()          
        person=Person.objects.get(id=person_id)      
        return render(request, 'polls/person.html', {'form': form.as_ul(),'person': person})        
    #return render(request, reverse('polls:persons',args = (person_id,)), {'form': form})        


def persons(request,person_id):    
    person = get_object_or_404(Person,id=person_id)
    context = {'person': person}
    return render(request,'polls/person.html',context)    

def details(request,question_id):    
    #try: 
    #    question = Question.objects.get(id=question_id)
    #except Question.DoesNotExist: 
    #    raise Http404("Question does not exist")
    
    question = get_object_or_404(Question,id=question_id)    
    context = {'question': question}
    return render(request,'polls/detail.html',context)    
    #return HttpResponse("This is detail view {}".format(question_id))

def results(request,question_id):
    question = get_object_or_404(Question,id=question_id)
    return render(request,'polls/result.html',{'question': question})
    #return HttpResponse("This is result view {}".format(question_id))

def vote(request,question_id):
    question = get_object_or_404(Question,id=question_id)
    try: 
        select_choice = question.choice_set.get(id=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist): 
        return render(request,'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice",        
        })    
    
    else: 
        
        select_choice.votes+=1
        select_choice.save()
        return HttpResponseRedirect(reverse('polls:results',args = (question_id,)))    


        
    #return HttpResponse("This is vote for question {}".format(question_id))
# Create your views here.

polls/templates/polls/detail.html
{% for name, value in question.get_field_question %}

	{% if value %}
	  <p> {{name}} => {{value}} </p>
	{% endif %}
{% endfor %}	

<h1 style="color:red">{{question.question_text}}</h1>

<ul>
	{% for choice in question.choice_set.all %}
		<li>{{choice.choice_text}}</li>
	{% endfor %}	
</ul>


<h1> This is detail view </h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />	
	<label for="choice {{ forloop.counter }}">{{ choice.choice_text }} </label> <br>
{% endfor %}

<input type="submit" value="Vote" />
</form>

polls/templates/polls/form.html
 <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ file_form }}
    <button type="submit">Upload</button>
  </form>

  <p><a href="{% url 'polls:index' %}">Return to home</a></p>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/css/main.css' %}" />

{% if latest_result %}
	<ul>	
	{% for question in latest_result %}
		<li>
			<a href="{% url 'polls:details' question.id %}">{{question.question_text}}</a>
		</li>
	{% endfor %}
	</ul>
{% else %}
	<p> No polls available </p>
	
{% endif %}		

{% if v_persons %}
	<ul>
	{% for person in v_persons %}
		<li>
			<a href="{% url 'polls:get_contactform' person.id %}">Update {{person.name}}-{{person.id}}</a>			
		</li>
	{% endfor %}
		
	</ul>
{% else %}	
	<p> No persons available for id = {{ person.id }}</p>
{% endif %}


{% if v_memberships %}
	<ul>
	{% for v_membership in v_memberships %}
		<li>
			<a href="{% url 'polls:details' v_membership.id %}"> {{v_membership.person.name}}</a>			
		</li>
	{% endfor %}
		
	</ul>
{% else %}	
	<p> No persons available for id = {{ v_membership.id }}</p>
{% endif %}


<h1> this is H1 css test</h1>

{% with p_id=1 %}
<form action="{% url 'polls:get_contactform' p_id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>
{% endwith %}

{% with p_id=1 %}
<a href="{% url  'polls:get_contactform' p_id %}">update_person_{{p_id}}</a>
{% endwith %}

<h1> This is form file upload test </h1>


<a href="{% url  'polls:file_form' %}">Test image form</a>

polls/templates/polls/person.html
<p> This is Person view </p>
{% if person %}
<p> Person ID = {{person.id}} and Person Name = {{person.name}}</p>
{% endif %}

{% if form %}
<form action="{% url 'polls:get_contactform' person.id %}" method="post">
{% csrf_token %}
{{ form }}
<input type="submit" value="Submit" />

</form>
{% endif %}

polls/templates/polls/result.html
<p> This is result page </p>

<h1> {{question.question_text}} </h1>
<ul>
{% for choice in question.choice_set.all %}

	<li> {{choice.choice_text}} -- {{ choice.votes }} vote{{ choice.votes|pluralize }} </li>

{% endfor %}	 

</ul>

<a href="{% url 'polls:details' question.id %}"> Vote again? </a>